include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: true
    require_trailing_commas: true
    sort_constructors_first: true
    avoid_print: true
